.TH FLOW
.SH NAME
flow \- Netflow Exporter
.SH SYNOPSIS
.B flow
[\fB\-f\fR \fIfilename\fR]
[\fB\-c\fR \fInetflow_collecor:port\fR]
[\fB\-a\fR \fIactive_timer\fR]
[\fB\-i\fR \fIinactive_timer\fR]
[\fB\-m\fR \fIcount\fR]
.SH DESCRIPTION
.B flow
creates flows and exports them to collector.
.SH OPTIONS
.TP
All values are optional.