.TH DHCP-STATS 1
.SH NAME
dhcp-stats \- Monitoring of DHCP communication
.SH SYNOPSIS
.B dhcp-stats
\fB\-r\fR <filename>
<ip-prefix>
[\fI \fR<ip-prefix> [...] ]
.br
.B dhcp-stats
\fB\-i\fR <interface-name>
<ip-prefix>
[\fI \fR<ip-prefix> [...] ]
.SH DESCRIPTION
.B dhcp-stats
gets statistics about the network prefix load considering the amount of allocated IP addresses. 
.br
When more than 50% of prefix addresses are seized, the tool informs the administrator on standard output and by logging through the syslog server.
.br

In the case of reading from a file, the program goes through the entire file and waits for termination by pressing any key. In the case of reading packets from the interface, it is necessary for the user to exit the program by pressing CTRL^C.
.SH OPTIONS
.TP
.BR \-r \ <filename> 
Statistics will be created from pcap files.\fR
.TP
\-i <interface-name> 
Statistics will be created from interface on which the program listens.\fR
.TP
<ip-prefix> 
The network range for which statistics will be generated.\fR
.br
More prefixes can be given.\fR
.TP
Statistics can not be created from pcap file and interface at the same time. There must be given only 1 of these parameters and at least one prefix is required! Prefix supports format N.N.N.N/P, where N is number between 0-255 and P is number between 0-30. There is no reason to use 31 and 32 prefix (31 has 0 MaxHosts and 32 has -2 MaxHosts).
.SH EXAMPLES
.BR ./dhcp-stats\ -r\ dhcp.pcap\ 192.168.1.0/24\ 192.168.0.0/22\ 172.16.32.0/24 \fR
.br
.BR ./dhcp-stats\ -i\ eth0\ 192.168.1.0/24\ 192.168.0.0/22\ 172.16.32.0/24 \fR